server:
  port: 8081  servlet:    context-path: /spring-security-oauth-server
spring:
  data:
    arangodb:      hosts: localhost:8529
      user: root
      password: root
      database: spring-demo

      
muon-kms: http://localhost:8087/muon-kms/
      